spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/business_db
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      enabled: true




  mail:
    host: smtp.gmail.com
    port: 587
    username: techandrewwilliam@gmail.com
    password: kxrd hizk yfry meiy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




azure:
  speech:
    key:
    region:


jwt:
  key:


server:
  port: 5050






